"""Initial schema

Revision ID: 5563da717ca2
Revises: 
Create Date: 2026-01-22 17:25:32.613048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5563da717ca2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_rating_scheme',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_rating_scheme_name'), 'credit_rating_scheme', ['name'], unique=True)
    op.create_table('document_chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunk_document_name'), 'document_chunk', ['document_name'], unique=False)
    op.create_index(op.f('ix_document_chunk_version'), 'document_chunk', ['version'], unique=False)
    op.create_table('interest_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term_months', sa.String(length=10), nullable=False),
    sa.Column('base_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interest_threshold_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reduction_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('applies_from_borrow_count', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalty_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('enabled', sa.String(length=10), nullable=False),
    sa.Column('date_added', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('stg_cycles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_deposits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_loans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percentage_interest', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('effective_month', sa.Date(), nullable=True),
    sa.Column('loan_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_penalties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('penalty_type_id', sa.String(length=36), nullable=False),
    sa.Column('date_issued', sa.DateTime(), nullable=True),
    sa.Column('approved', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_repayments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('nrc_number', sa.String(length=50), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TREASURER', 'MEMBER', 'COMPLIANCE', name='userroleenum'), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('first_name_next_of_kin', sa.String(length=100), nullable=True),
    sa.Column('last_name_next_of_kin', sa.String(length=100), nullable=True),
    sa.Column('phone_number_next_of_kin', sa.String(length=20), nullable=True),
    sa.Column('date_joined', sa.DateTime(), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_nrc_number'), 'user', ['nrc_number'], unique=True)
    op.create_table('vb_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_audit_log_timestamp'), 'ai_audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ai_audit_log_user_id'), 'ai_audit_log', ['user_id'], unique=False)
    op.create_table('collateral_policy_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('policy_text', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('committee_assignment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_assignment_role_id'), 'committee_assignment', ['role_id'], unique=False)
    op.create_index(op.f('ix_committee_assignment_user_id'), 'committee_assignment', ['user_id'], unique=False)
    op.create_table('constitution_document_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('document_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_rating_tier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('tier_name', sa.String(length=50), nullable=False),
    sa.Column('tier_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['credit_rating_scheme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_rating_tier_scheme_id'), 'credit_rating_tier', ['scheme_id'], unique=False)
    op.create_table('cycle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', name='cyclestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_year'), 'cycle', ['year'], unique=True)
    op.create_table('document_embedding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_embedding_chunk_id'), 'document_embedding', ['chunk_id'], unique=True)
    op.create_table('id_map_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('old_user_id', sa.String(length=36), nullable=False),
    sa.Column('new_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['new_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_id_map_user_new_user_id'), 'id_map_user', ['new_user_id'], unique=True)
    op.create_index(op.f('ix_id_map_user_old_user_id'), 'id_map_user', ['old_user_id'], unique=True)
    op.create_table('member_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='memberstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('activated_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['activated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_profile_user_id'), 'member_profile', ['user_id'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)
    op.create_table('user_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False)
    op.create_table('borrowing_limit_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['credit_rating_tier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrowing_limit_policy_tier_id'), 'borrowing_limit_policy', ['tier_id'], unique=False)
    op.create_table('collateral_asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('title_document_path', sa.String(length=500), nullable=True),
    sa.Column('policy_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['collateral_policy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collateral_asset_member_id'), 'collateral_asset', ['member_id'], unique=False)
    op.create_table('cycle_phase',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('phase_type', sa.Enum('DECLARATION', 'LOAN_APPLICATION', 'DEPOSITS', 'PAYOUT', 'SHAREOUT', name='phasetype'), nullable=False),
    sa.Column('phase_order', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'phase_type', name='uq_cycle_phase_type')
    )
    op.create_index(op.f('ix_cycle_phase_cycle_id'), 'cycle_phase', ['cycle_id'], unique=False)
    op.create_table('declaration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('effective_month', sa.Date(), nullable=False),
    sa.Column('declared_savings_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('declared_social_fund', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('declared_admin_fund', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('declared_penalties', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('declared_interest_on_loan', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('declared_loan_repayment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROOF', 'APPROVED', 'REJECTED', name='declarationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declaration_cycle_id'), 'declaration', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_declaration_member_id'), 'declaration', ['member_id'], unique=False)
    op.create_table('id_map_member',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('old_member_id', sa.String(length=36), nullable=False),
    sa.Column('new_member_profile_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['new_member_profile_id'], ['member_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_id_map_member_new_member_profile_id'), 'id_map_member', ['new_member_profile_id'], unique=True)
    op.create_index(op.f('ix_id_map_member_old_member_id'), 'id_map_member', ['old_member_id'], unique=True)
    op.create_table('journal_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('source_ref', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_cycle_id'), 'journal_entry', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_entry_date'), 'journal_entry', ['entry_date'], unique=False)
    op.create_table('ledger_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'INCOME', 'EXPENSE', 'EQUITY', name='accounttype'), nullable=False),
    sa.Column('parent_account_id', sa.UUID(), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.ForeignKeyConstraint(['parent_account_id'], ['ledger_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_account_account_code'), 'ledger_account', ['account_code'], unique=True)
    op.create_index(op.f('ix_ledger_account_member_id'), 'ledger_account', ['member_id'], unique=False)
    op.create_table('loan_application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('term_months', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='loanapplicationstatus'), nullable=False),
    sa.Column('application_date', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_application_cycle_id'), 'loan_application', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_loan_application_member_id'), 'loan_application', ['member_id'], unique=False)
    op.create_table('member_credit_rating',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['credit_rating_scheme.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['credit_rating_tier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_credit_rating_cycle_id'), 'member_credit_rating', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_member_credit_rating_member_id'), 'member_credit_rating', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_credit_rating_scheme_id'), 'member_credit_rating', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_member_credit_rating_tier_id'), 'member_credit_rating', ['tier_id'], unique=False)
    op.create_table('member_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_profile_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='memberstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='memberstatus'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['member_profile_id'], ['member_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_status_history_member_profile_id'), 'member_status_history', ['member_profile_id'], unique=False)
    op.create_table('posting_lock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('locked_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['locked_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posting_lock_cycle_id'), 'posting_lock', ['cycle_id'], unique=True)
    op.create_table('collateral_valuation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('valuation_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valued_by', sa.UUID(), nullable=False),
    sa.Column('valued_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['collateral_asset.id'], ),
    sa.ForeignKeyConstraint(['valued_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collateral_valuation_asset_id'), 'collateral_valuation', ['asset_id'], unique=False)
    op.create_table('deposit_proof',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('declaration_id', sa.UUID(), nullable=True),
    sa.Column('upload_path', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['declaration_id'], ['declaration.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_proof_cycle_id'), 'deposit_proof', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_deposit_proof_declaration_id'), 'deposit_proof', ['declaration_id'], unique=False)
    op.create_index(op.f('ix_deposit_proof_member_id'), 'deposit_proof', ['member_id'], unique=False)
    op.create_table('journal_line',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('ledger_account_id', sa.UUID(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['ledger_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_journal_line_account_date', 'journal_line', ['ledger_account_id', 'journal_entry_id'], unique=False)
    op.create_index(op.f('ix_journal_line_journal_entry_id'), 'journal_line', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_journal_line_ledger_account_id'), 'journal_line', ['ledger_account_id'], unique=False)
    op.create_table('loan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('percentage_interest', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_month', sa.Date(), nullable=True),
    sa.Column('repayment_start_date', sa.Date(), nullable=True),
    sa.Column('repayment_end_date', sa.Date(), nullable=True),
    sa.Column('number_of_instalments', sa.String(length=10), nullable=True),
    sa.Column('loan_status', sa.Enum('PENDING', 'APPROVED', 'DISBURSED', 'CLOSED', 'OPEN', 'WITHDRAWN', 'REJECTED', name='loanstatus'), nullable=False),
    sa.Column('disbursement_date', sa.Date(), nullable=True),
    sa.Column('disbursement_journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_application.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['disbursement_journal_entry_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_application_id'), 'loan', ['application_id'], unique=True)
    op.create_index(op.f('ix_loan_cycle_id'), 'loan', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_loan_member_id'), 'loan', ['member_id'], unique=False)
    op.create_table('penalty_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('penalty_type_id', sa.UUID(), nullable=False),
    sa.Column('date_issued', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'POSTED', name='penaltyrecordstatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.ForeignKeyConstraint(['penalty_type_id'], ['penalty_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penalty_record_journal_entry_id'), 'penalty_record', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_penalty_record_member_id'), 'penalty_record', ['member_id'], unique=False)
    op.create_index(op.f('ix_penalty_record_penalty_type_id'), 'penalty_record', ['penalty_type_id'], unique=False)
    op.create_table('policy_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('interest_policy_id', sa.UUID(), nullable=True),
    sa.Column('interest_threshold_policy_id', sa.UUID(), nullable=True),
    sa.Column('borrowing_limit_policy_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['borrowing_limit_policy_id'], ['borrowing_limit_policy.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['interest_policy_id'], ['interest_policy.id'], ),
    sa.ForeignKeyConstraint(['interest_threshold_policy_id'], ['interest_threshold_policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_version_cycle_id'), 'policy_version', ['cycle_id'], unique=False)
    op.create_table('collateral_hold',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('hold_start', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('hold_end', sa.DateTime(), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['collateral_asset.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collateral_hold_asset_id'), 'collateral_hold', ['asset_id'], unique=False)
    op.create_index(op.f('ix_collateral_hold_loan_id'), 'collateral_hold', ['loan_id'], unique=False)
    op.create_table('deposit_approval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deposit_proof_id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deposit_proof_id'], ['deposit_proof.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_approval_deposit_proof_id'), 'deposit_approval', ['deposit_proof_id'], unique=True)
    op.create_index(op.f('ix_deposit_approval_journal_entry_id'), 'deposit_approval', ['journal_entry_id'], unique=True)
    op.create_table('id_map_loan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('old_loan_id', sa.String(length=36), nullable=False),
    sa.Column('new_loan_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['new_loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_id_map_loan_new_loan_id'), 'id_map_loan', ['new_loan_id'], unique=True)
    op.create_index(op.f('ix_id_map_loan_old_loan_id'), 'id_map_loan', ['old_loan_id'], unique=True)
    op.create_table('repayment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('repayment_date', sa.Date(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repayment_journal_entry_id'), 'repayment', ['journal_entry_id'], unique=True)
    op.create_index(op.f('ix_repayment_loan_id'), 'repayment', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repayment_loan_id'), table_name='repayment')
    op.drop_index(op.f('ix_repayment_journal_entry_id'), table_name='repayment')
    op.drop_table('repayment')
    op.drop_index(op.f('ix_id_map_loan_old_loan_id'), table_name='id_map_loan')
    op.drop_index(op.f('ix_id_map_loan_new_loan_id'), table_name='id_map_loan')
    op.drop_table('id_map_loan')
    op.drop_index(op.f('ix_deposit_approval_journal_entry_id'), table_name='deposit_approval')
    op.drop_index(op.f('ix_deposit_approval_deposit_proof_id'), table_name='deposit_approval')
    op.drop_table('deposit_approval')
    op.drop_index(op.f('ix_collateral_hold_loan_id'), table_name='collateral_hold')
    op.drop_index(op.f('ix_collateral_hold_asset_id'), table_name='collateral_hold')
    op.drop_table('collateral_hold')
    op.drop_index(op.f('ix_policy_version_cycle_id'), table_name='policy_version')
    op.drop_table('policy_version')
    op.drop_index(op.f('ix_penalty_record_penalty_type_id'), table_name='penalty_record')
    op.drop_index(op.f('ix_penalty_record_member_id'), table_name='penalty_record')
    op.drop_index(op.f('ix_penalty_record_journal_entry_id'), table_name='penalty_record')
    op.drop_table('penalty_record')
    op.drop_index(op.f('ix_loan_member_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_cycle_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_application_id'), table_name='loan')
    op.drop_table('loan')
    op.drop_index(op.f('ix_journal_line_ledger_account_id'), table_name='journal_line')
    op.drop_index(op.f('ix_journal_line_journal_entry_id'), table_name='journal_line')
    op.drop_index('idx_journal_line_account_date', table_name='journal_line')
    op.drop_table('journal_line')
    op.drop_index(op.f('ix_deposit_proof_member_id'), table_name='deposit_proof')
    op.drop_index(op.f('ix_deposit_proof_declaration_id'), table_name='deposit_proof')
    op.drop_index(op.f('ix_deposit_proof_cycle_id'), table_name='deposit_proof')
    op.drop_table('deposit_proof')
    op.drop_index(op.f('ix_collateral_valuation_asset_id'), table_name='collateral_valuation')
    op.drop_table('collateral_valuation')
    op.drop_index(op.f('ix_posting_lock_cycle_id'), table_name='posting_lock')
    op.drop_table('posting_lock')
    op.drop_index(op.f('ix_member_status_history_member_profile_id'), table_name='member_status_history')
    op.drop_table('member_status_history')
    op.drop_index(op.f('ix_member_credit_rating_tier_id'), table_name='member_credit_rating')
    op.drop_index(op.f('ix_member_credit_rating_scheme_id'), table_name='member_credit_rating')
    op.drop_index(op.f('ix_member_credit_rating_member_id'), table_name='member_credit_rating')
    op.drop_index(op.f('ix_member_credit_rating_cycle_id'), table_name='member_credit_rating')
    op.drop_table('member_credit_rating')
    op.drop_index(op.f('ix_loan_application_member_id'), table_name='loan_application')
    op.drop_index(op.f('ix_loan_application_cycle_id'), table_name='loan_application')
    op.drop_table('loan_application')
    op.drop_index(op.f('ix_ledger_account_member_id'), table_name='ledger_account')
    op.drop_index(op.f('ix_ledger_account_account_code'), table_name='ledger_account')
    op.drop_table('ledger_account')
    op.drop_index(op.f('ix_journal_entry_entry_date'), table_name='journal_entry')
    op.drop_index(op.f('ix_journal_entry_cycle_id'), table_name='journal_entry')
    op.drop_table('journal_entry')
    op.drop_index(op.f('ix_id_map_member_old_member_id'), table_name='id_map_member')
    op.drop_index(op.f('ix_id_map_member_new_member_profile_id'), table_name='id_map_member')
    op.drop_table('id_map_member')
    op.drop_index(op.f('ix_declaration_member_id'), table_name='declaration')
    op.drop_index(op.f('ix_declaration_cycle_id'), table_name='declaration')
    op.drop_table('declaration')
    op.drop_index(op.f('ix_cycle_phase_cycle_id'), table_name='cycle_phase')
    op.drop_table('cycle_phase')
    op.drop_index(op.f('ix_collateral_asset_member_id'), table_name='collateral_asset')
    op.drop_table('collateral_asset')
    op.drop_index(op.f('ix_borrowing_limit_policy_tier_id'), table_name='borrowing_limit_policy')
    op.drop_table('borrowing_limit_policy')
    op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_member_profile_user_id'), table_name='member_profile')
    op.drop_table('member_profile')
    op.drop_index(op.f('ix_id_map_user_old_user_id'), table_name='id_map_user')
    op.drop_index(op.f('ix_id_map_user_new_user_id'), table_name='id_map_user')
    op.drop_table('id_map_user')
    op.drop_index(op.f('ix_document_embedding_chunk_id'), table_name='document_embedding')
    op.drop_table('document_embedding')
    op.drop_index(op.f('ix_cycle_year'), table_name='cycle')
    op.drop_table('cycle')
    op.drop_index(op.f('ix_credit_rating_tier_scheme_id'), table_name='credit_rating_tier')
    op.drop_table('credit_rating_tier')
    op.drop_table('constitution_document_version')
    op.drop_index(op.f('ix_committee_assignment_user_id'), table_name='committee_assignment')
    op.drop_index(op.f('ix_committee_assignment_role_id'), table_name='committee_assignment')
    op.drop_table('committee_assignment')
    op.drop_table('collateral_policy_version')
    op.drop_index(op.f('ix_ai_audit_log_user_id'), table_name='ai_audit_log')
    op.drop_index(op.f('ix_ai_audit_log_timestamp'), table_name='ai_audit_log')
    op.drop_table('ai_audit_log')
    op.drop_table('vb_group')
    op.drop_index(op.f('ix_user_nrc_number'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('stg_repayments')
    op.drop_table('stg_penalties')
    op.drop_table('stg_members')
    op.drop_table('stg_loans')
    op.drop_table('stg_deposits')
    op.drop_table('stg_cycles')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_table('penalty_type')
    op.drop_table('interest_threshold_policy')
    op.drop_table('interest_policy')
    op.drop_index(op.f('ix_document_chunk_version'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_document_name'), table_name='document_chunk')
    op.drop_table('document_chunk')
    op.drop_index(op.f('ix_credit_rating_scheme_name'), table_name='credit_rating_scheme')
    op.drop_table('credit_rating_scheme')
    # ### end Alembic commands ###
