"""add_payment_request_table

Revision ID: 6506e8a1d97f
Revises: a1b2c3d4e5f6
Create Date: 2026-04-08 13:12:28.188206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6506e8a1d97f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('committee_payment', 'social_support', 'admin_cost', 'end_of_year_payout', name='paymentcategory', native_enum=False), nullable=False),
    sa.Column('source_account_code', sa.String(length=20), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=200), nullable=False),
    sa.Column('beneficiary_member_id', sa.Uuid(), nullable=True),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'executed', 'cancelled', name='paymentrequeststatus', native_enum=False), nullable=False),
    sa.Column('initiated_by', sa.Uuid(), nullable=False),
    sa.Column('initiated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('executed_by', sa.Uuid(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['beneficiary_member_id'], ['member_profile.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['executed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.create_index('idx_payment_request_cycle_id', ['cycle_id'], unique=False)
        batch_op.create_index('idx_payment_request_initiated_by', ['initiated_by'], unique=False)
        batch_op.create_index('idx_payment_request_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_request', schema=None) as batch_op:
        batch_op.drop_index('idx_payment_request_status')
        batch_op.drop_index('idx_payment_request_initiated_by')
        batch_op.drop_index('idx_payment_request_cycle_id')

    op.drop_table('payment_request')
    # ### end Alembic commands ###
