"""initial_mysql_schema

Revision ID: c0316f1ba32a
Revises: 
Create Date: 2026-02-17 20:17:52.827496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = 'c0316f1ba32a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_rating_scheme',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_rating_scheme', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_rating_scheme_name'), ['name'], unique=True)

    op.create_table('document_chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunk_document_name'), ['document_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunk_version'), ['version'], unique=False)

    op.create_table('interest_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('term_months', sa.String(length=10), nullable=False),
    sa.Column('base_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interest_threshold_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reduction_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('applies_from_borrow_count', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalty_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('enabled', sa.String(length=10), nullable=False),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    op.create_table('stg_cycles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_deposits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_loans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percentage_interest', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('effective_month', sa.Date(), nullable=True),
    sa.Column('loan_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_penalties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('penalty_type_id', sa.String(length=36), nullable=False),
    sa.Column('date_issued', sa.DateTime(), nullable=True),
    sa.Column('approved', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stg_repayments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('nrc_number', sa.String(length=50), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'treasurer', 'member', 'compliance', 'chairman', name='userroleenum', native_enum=False), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('first_name_next_of_kin', sa.String(length=100), nullable=True),
    sa.Column('last_name_next_of_kin', sa.String(length=100), nullable=True),
    sa.Column('phone_number_next_of_kin', sa.String(length=20), nullable=True),
    sa.Column('date_joined', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_nrc_number'), ['nrc_number'], unique=True)

    op.create_table('vb_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_audit_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('collateral_policy_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('policy_text', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('committee_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('committee_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_committee_assignment_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_committee_assignment_user_id'), ['user_id'], unique=False)

    op.create_table('constitution_document_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('document_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_rating_tier',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('tier_name', sa.String(length=50), nullable=False),
    sa.Column('tier_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['credit_rating_scheme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_rating_tier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_rating_tier_scheme_id'), ['scheme_id'], unique=False)

    op.create_table('cycle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='cyclestatus', native_enum=False), nullable=False),
    sa.Column('social_fund_required', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('admin_fund_required', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_year'), ['year'], unique=True)

    op.create_table('document_embedding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', app.db.types.MySQLVector(1536), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_embedding_chunk_id'), ['chunk_id'], unique=True)

    op.create_table('id_map_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('old_user_id', sa.String(length=36), nullable=False),
    sa.Column('new_user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['new_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('id_map_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_id_map_user_new_user_id'), ['new_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_id_map_user_old_user_id'), ['old_user_id'], unique=True)

    op.create_table('member_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='memberstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('activated_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['activated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_profile_user_id'), ['user_id'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_setting_key'), ['setting_key'], unique=True)

    op.create_table('user_role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_user_id'), ['user_id'], unique=False)

    op.create_table('borrowing_limit_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tier_id', sa.Uuid(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['credit_rating_tier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('borrowing_limit_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_borrowing_limit_policy_tier_id'), ['tier_id'], unique=False)

    op.create_table('collateral_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('title_document_path', sa.String(length=500), nullable=True),
    sa.Column('policy_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['collateral_policy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collateral_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collateral_asset_member_id'), ['member_id'], unique=False)

    op.create_table('credit_rating_interest_range',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tier_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('term_months', sa.String(length=10), nullable=True),
    sa.Column('effective_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['credit_rating_tier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_rating_interest_range', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_rating_interest_range_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_rating_interest_range_tier_id'), ['tier_id'], unique=False)

    op.create_table('cycle_phase',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('phase_type', sa.Enum('declaration', 'loan_application', 'deposits', 'payout', 'shareout', name='phasetype', native_enum=False), nullable=False),
    sa.Column('phase_order', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('monthly_start_day', sa.Integer(), nullable=True),
    sa.Column('monthly_end_day', sa.Integer(), nullable=True),
    sa.Column('penalty_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('penalty_type_id', sa.Uuid(), nullable=True),
    sa.Column('auto_apply_penalty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['penalty_type_id'], ['penalty_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'phase_type', name='uq_cycle_phase_type')
    )
    with op.batch_alter_table('cycle_phase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_phase_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('declaration',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('effective_month', sa.Date(), nullable=False),
    sa.Column('declared_savings_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('declared_social_fund', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('declared_admin_fund', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('declared_penalties', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('declared_interest_on_loan', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('declared_loan_repayment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'proof', 'approved', 'rejected', name='declarationstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('declaration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_declaration_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_declaration_member_id'), ['member_id'], unique=False)

    op.create_table('id_map_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('old_member_id', sa.String(length=36), nullable=False),
    sa.Column('new_member_profile_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['new_member_profile_id'], ['member_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('id_map_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_id_map_member_new_member_profile_id'), ['new_member_profile_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_id_map_member_old_member_id'), ['old_member_id'], unique=True)

    op.create_table('journal_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.Column('source_ref', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('reversed_by', sa.Uuid(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['reversed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_entry_date'), ['entry_date'], unique=False)

    op.create_table('ledger_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.Enum('asset', 'liability', 'income', 'expense', 'equity', name='accounttype', native_enum=False), nullable=False),
    sa.Column('parent_account_id', sa.Uuid(), nullable=True),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.ForeignKeyConstraint(['parent_account_id'], ['ledger_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_account_account_code'), ['account_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_ledger_account_member_id'), ['member_id'], unique=False)

    op.create_table('loan_application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('term_months', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'withdrawn', name='loanapplicationstatus', native_enum=False), nullable=False),
    sa.Column('application_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_application_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_application_member_id'), ['member_id'], unique=False)

    op.create_table('member_credit_rating',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('tier_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['credit_rating_scheme.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['credit_rating_tier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_credit_rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_credit_rating_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_credit_rating_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_credit_rating_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_credit_rating_tier_id'), ['tier_id'], unique=False)

    op.create_table('member_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_profile_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.Enum('active', 'inactive', name='memberstatus', native_enum=False), nullable=True),
    sa.Column('new_status', sa.Enum('active', 'inactive', name='memberstatus', native_enum=False), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['member_profile_id'], ['member_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_status_history_member_profile_id'), ['member_profile_id'], unique=False)

    op.create_table('posting_lock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('locked_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['locked_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posting_lock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posting_lock_cycle_id'), ['cycle_id'], unique=True)

    op.create_table('collateral_valuation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('valuation_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valued_by', sa.Uuid(), nullable=False),
    sa.Column('valued_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['collateral_asset.id'], ),
    sa.ForeignKeyConstraint(['valued_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collateral_valuation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collateral_valuation_asset_id'), ['asset_id'], unique=False)

    op.create_table('deposit_proof',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('declaration_id', sa.Uuid(), nullable=True),
    sa.Column('upload_path', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('treasurer_comment', sa.Text(), nullable=True),
    sa.Column('member_response', sa.Text(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['declaration_id'], ['declaration.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deposit_proof', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deposit_proof_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deposit_proof_declaration_id'), ['declaration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deposit_proof_member_id'), ['member_id'], unique=False)

    op.create_table('journal_line',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('ledger_account_id', sa.Uuid(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['ledger_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_line', schema=None) as batch_op:
        batch_op.create_index('idx_journal_line_account_date', ['ledger_account_id', 'journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_line_journal_entry_id'), ['journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_line_ledger_account_id'), ['ledger_account_id'], unique=False)

    op.create_table('loan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('percentage_interest', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_month', sa.Date(), nullable=True),
    sa.Column('repayment_start_date', sa.Date(), nullable=True),
    sa.Column('repayment_end_date', sa.Date(), nullable=True),
    sa.Column('number_of_instalments', sa.String(length=10), nullable=True),
    sa.Column('loan_status', sa.Enum('pending', 'approved', 'disbursed', 'closed', 'open', 'withdrawn', 'rejected', name='loanstatus', native_enum=False), nullable=False),
    sa.Column('disbursement_date', sa.Date(), nullable=True),
    sa.Column('disbursement_journal_entry_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_application.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['disbursement_journal_entry_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_application_id'), ['application_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_loan_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loan_member_id'), ['member_id'], unique=False)

    op.create_table('penalty_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('penalty_type_id', sa.Uuid(), nullable=False),
    sa.Column('date_issued', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', app.models.transaction.PenaltyRecordStatusType(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_profile.id'], ),
    sa.ForeignKeyConstraint(['penalty_type_id'], ['penalty_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penalty_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penalty_record_journal_entry_id'), ['journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_penalty_record_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_penalty_record_penalty_type_id'), ['penalty_type_id'], unique=False)

    op.create_table('policy_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('interest_policy_id', sa.Uuid(), nullable=True),
    sa.Column('interest_threshold_policy_id', sa.Uuid(), nullable=True),
    sa.Column('borrowing_limit_policy_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['borrowing_limit_policy_id'], ['borrowing_limit_policy.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycle.id'], ),
    sa.ForeignKeyConstraint(['interest_policy_id'], ['interest_policy.id'], ),
    sa.ForeignKeyConstraint(['interest_threshold_policy_id'], ['interest_threshold_policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_version_cycle_id'), ['cycle_id'], unique=False)

    op.create_table('collateral_hold',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('hold_start', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('hold_end', sa.DateTime(), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['collateral_asset.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collateral_hold', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collateral_hold_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collateral_hold_loan_id'), ['loan_id'], unique=False)

    op.create_table('deposit_approval',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deposit_proof_id', sa.Uuid(), nullable=False),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deposit_proof_id'], ['deposit_proof.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deposit_approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deposit_approval_deposit_proof_id'), ['deposit_proof_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_deposit_approval_journal_entry_id'), ['journal_entry_id'], unique=True)

    op.create_table('id_map_loan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('old_loan_id', sa.String(length=36), nullable=False),
    sa.Column('new_loan_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['new_loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('id_map_loan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_id_map_loan_new_loan_id'), ['new_loan_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_id_map_loan_old_loan_id'), ['old_loan_id'], unique=True)

    op.create_table('repayment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('repayment_date', sa.Date(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('journal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repayment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repayment_journal_entry_id'), ['journal_entry_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_repayment_loan_id'), ['loan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repayment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repayment_loan_id'))
        batch_op.drop_index(batch_op.f('ix_repayment_journal_entry_id'))

    op.drop_table('repayment')
    with op.batch_alter_table('id_map_loan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_id_map_loan_old_loan_id'))
        batch_op.drop_index(batch_op.f('ix_id_map_loan_new_loan_id'))

    op.drop_table('id_map_loan')
    with op.batch_alter_table('deposit_approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deposit_approval_journal_entry_id'))
        batch_op.drop_index(batch_op.f('ix_deposit_approval_deposit_proof_id'))

    op.drop_table('deposit_approval')
    with op.batch_alter_table('collateral_hold', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collateral_hold_loan_id'))
        batch_op.drop_index(batch_op.f('ix_collateral_hold_asset_id'))

    op.drop_table('collateral_hold')
    with op.batch_alter_table('policy_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_version_cycle_id'))

    op.drop_table('policy_version')
    with op.batch_alter_table('penalty_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penalty_record_penalty_type_id'))
        batch_op.drop_index(batch_op.f('ix_penalty_record_member_id'))
        batch_op.drop_index(batch_op.f('ix_penalty_record_journal_entry_id'))

    op.drop_table('penalty_record')
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_member_id'))
        batch_op.drop_index(batch_op.f('ix_loan_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_loan_application_id'))

    op.drop_table('loan')
    with op.batch_alter_table('journal_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_line_ledger_account_id'))
        batch_op.drop_index(batch_op.f('ix_journal_line_journal_entry_id'))
        batch_op.drop_index('idx_journal_line_account_date')

    op.drop_table('journal_line')
    with op.batch_alter_table('deposit_proof', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deposit_proof_member_id'))
        batch_op.drop_index(batch_op.f('ix_deposit_proof_declaration_id'))
        batch_op.drop_index(batch_op.f('ix_deposit_proof_cycle_id'))

    op.drop_table('deposit_proof')
    with op.batch_alter_table('collateral_valuation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collateral_valuation_asset_id'))

    op.drop_table('collateral_valuation')
    with op.batch_alter_table('posting_lock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posting_lock_cycle_id'))

    op.drop_table('posting_lock')
    with op.batch_alter_table('member_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_status_history_member_profile_id'))

    op.drop_table('member_status_history')
    with op.batch_alter_table('member_credit_rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_credit_rating_tier_id'))
        batch_op.drop_index(batch_op.f('ix_member_credit_rating_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_member_credit_rating_member_id'))
        batch_op.drop_index(batch_op.f('ix_member_credit_rating_cycle_id'))

    op.drop_table('member_credit_rating')
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_application_member_id'))
        batch_op.drop_index(batch_op.f('ix_loan_application_cycle_id'))

    op.drop_table('loan_application')
    with op.batch_alter_table('ledger_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_account_member_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_account_account_code'))

    op.drop_table('ledger_account')
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_entry_date'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_cycle_id'))

    op.drop_table('journal_entry')
    with op.batch_alter_table('id_map_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_id_map_member_old_member_id'))
        batch_op.drop_index(batch_op.f('ix_id_map_member_new_member_profile_id'))

    op.drop_table('id_map_member')
    with op.batch_alter_table('declaration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_declaration_member_id'))
        batch_op.drop_index(batch_op.f('ix_declaration_cycle_id'))

    op.drop_table('declaration')
    with op.batch_alter_table('cycle_phase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_phase_cycle_id'))

    op.drop_table('cycle_phase')
    with op.batch_alter_table('credit_rating_interest_range', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_rating_interest_range_tier_id'))
        batch_op.drop_index(batch_op.f('ix_credit_rating_interest_range_cycle_id'))

    op.drop_table('credit_rating_interest_range')
    with op.batch_alter_table('collateral_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collateral_asset_member_id'))

    op.drop_table('collateral_asset')
    with op.batch_alter_table('borrowing_limit_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_borrowing_limit_policy_tier_id'))

    op.drop_table('borrowing_limit_policy')
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_role_role_id'))

    op.drop_table('user_role')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_setting_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('member_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_profile_user_id'))

    op.drop_table('member_profile')
    with op.batch_alter_table('id_map_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_id_map_user_old_user_id'))
        batch_op.drop_index(batch_op.f('ix_id_map_user_new_user_id'))

    op.drop_table('id_map_user')
    with op.batch_alter_table('document_embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_embedding_chunk_id'))

    op.drop_table('document_embedding')
    with op.batch_alter_table('cycle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_year'))

    op.drop_table('cycle')
    with op.batch_alter_table('credit_rating_tier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_rating_tier_scheme_id'))

    op.drop_table('credit_rating_tier')
    op.drop_table('constitution_document_version')
    with op.batch_alter_table('committee_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_committee_assignment_user_id'))
        batch_op.drop_index(batch_op.f('ix_committee_assignment_role_id'))

    op.drop_table('committee_assignment')
    op.drop_table('collateral_policy_version')
    with op.batch_alter_table('ai_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_audit_log_timestamp'))

    op.drop_table('ai_audit_log')
    op.drop_table('vb_group')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_nrc_number'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('stg_repayments')
    op.drop_table('stg_penalties')
    op.drop_table('stg_members')
    op.drop_table('stg_loans')
    op.drop_table('stg_deposits')
    op.drop_table('stg_cycles')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    op.drop_table('role')
    op.drop_table('penalty_type')
    op.drop_table('interest_threshold_policy')
    op.drop_table('interest_policy')
    with op.batch_alter_table('document_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunk_version'))
        batch_op.drop_index(batch_op.f('ix_document_chunk_document_name'))

    op.drop_table('document_chunk')
    with op.batch_alter_table('credit_rating_scheme', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_rating_scheme_name'))

    op.drop_table('credit_rating_scheme')
    # ### end Alembic commands ###
